# Generated by Django 3.0.5 on 2020-04-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
